#!/usr/bin/env bash

#
# Copyright (c) VMware, Inc. 2022. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

echo "Running concourse-metadata script" 1>&2

SCRIPT_INPUT='/tmp/input'
cat > $SCRIPT_INPUT <&0 # STDIN params

OUTPUT_STRING="[ ]"

echo $OUTPUT_STRING

exit 0
