#!/usr/bin/env bash

#
# Copyright (c) VMware, Inc. 2022. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

SCRIPT_INPUT='/tmp/input'
cat > $SCRIPT_INPUT <&0 # STDIN params

VERSION=$(uuidgen)

OUTPUT_STRING="{ \"version\": { \"ref\": \"$VERSION\" } }"

echo $OUTPUT_STRING

exit 0
